"""init-3

Revision ID: 279996fd2b37
Revises: 
Create Date: 2025-07-15 15:26:41.763406

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279996fd2b37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('UserId', sa.Uuid(), nullable=False),
    sa.Column('UserName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('EmailId', sa.String(length=255), nullable=False),
    sa.Column('Password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('EmailId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('hero')
    # ### end Alembic commands ###
