"""postgre_init

Revision ID: e66520a666b9
Revises: 
Create Date: 2025-07-23 18:37:42.612298

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66520a666b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taskdescription', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('taskstatus', sa.Integer(), nullable=False),
    sa.Column('taskpriority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('taskid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emailid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('emailid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('todo')
    # ### end Alembic commands ###
